// <auto-generated />
using System;
using Biblioteca.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Biblioteca.Migrations
{
    [DbContext(typeof(AppDataContext))]
    partial class AppDataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("Biblioteca.Models.Autor", b =>
                {
                    b.Property<int>("IdAutor")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Bibliografia")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("Falecimento")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("Nascimento")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("IdAutor");

                    b.ToTable("Autores");

                    b.HasData(
                        new
                        {
                            IdAutor = 1,
                            Bibliografia = "Nasceu em Boston, EUA. Publicou seu primeiro livro 'Tamerlane and Other Poems' em 1827.",
                            Nascimento = new DateTime(1809, 1, 19, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Nome = "Edgar Allan Poe"
                        },
                        new
                        {
                            IdAutor = 2,
                            Bibliografia = "Nasceu em Edimburgo, Escócia. Publicou seu primeiro livro 'A Study in Scarlet' em 1887.",
                            Nascimento = new DateTime(1859, 5, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Nome = "Arthur Conan Doyle"
                        },
                        new
                        {
                            IdAutor = 3,
                            Bibliografia = "Nasceu em Providence, EUA. Publicou seu primeiro livro 'The Alchemist' em 1916.",
                            Nascimento = new DateTime(1890, 8, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Nome = "H. P. Lovecraft"
                        },
                        new
                        {
                            IdAutor = 4,
                            Bibliografia = "Nasceu em Londres, Inglaterra. Publicou seu primeiro livro 'Frankenstein' em 1818.",
                            Nascimento = new DateTime(1797, 8, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Nome = "Mary Shelly"
                        },
                        new
                        {
                            IdAutor = 5,
                            Bibliografia = "Nasceu em Torquay, Inglaterra. Publicou seu primeiro livro 'The Mysterious Affair at Styles' em 1920.",
                            Nascimento = new DateTime(1890, 9, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Nome = "Agatha Christie"
                        },
                        new
                        {
                            IdAutor = 6,
                            Bibliografia = "Nasceu em Portland, EUA. Publicou seu primeiro livro 'Carrie' em 1974.",
                            Nascimento = new DateTime(1947, 9, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Nome = "Stephen King"
                        },
                        new
                        {
                            IdAutor = 7,
                            Bibliografia = "Nasceu em Dublin, Irlanda. Publicou seu primeiro livro 'The Snake's Pass' em 1890.",
                            Nascimento = new DateTime(1847, 11, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Nome = "Bram Stoker"
                        });
                });

            modelBuilder.Entity("Biblioteca.Models.Emprestimo", b =>
                {
                    b.Property<int>("IdEmprestimo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime>("DataDevolucao")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("DataEmprestimo")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("IdLivro")
                        .HasColumnType("int");

                    b.Property<int>("IdUsuario")
                        .HasColumnType("int");

                    b.HasKey("IdEmprestimo");

                    b.HasIndex("IdLivro");

                    b.HasIndex("IdUsuario");

                    b.ToTable("Emprestimos");
                });

            modelBuilder.Entity("Biblioteca.Models.Genero", b =>
                {
                    b.Property<int>("IdGenero")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("IdGenero");

                    b.ToTable("Generos");

                    b.HasData(
                        new
                        {
                            IdGenero = 1,
                            Nome = "Terror"
                        },
                        new
                        {
                            IdGenero = 2,
                            Nome = "Romance"
                        },
                        new
                        {
                            IdGenero = 3,
                            Nome = "Investigação Policial"
                        });
                });

            modelBuilder.Entity("Biblioteca.Models.Livro", b =>
                {
                    b.Property<int>("IdLivro")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("AnoPublicacao")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("FotoLivro")
                        .HasColumnType("longtext");

                    b.Property<int>("IdAutor")
                        .HasColumnType("int");

                    b.Property<int>("IdGenero")
                        .HasColumnType("int");

                    b.Property<int>("NPaginas")
                        .HasColumnType("int");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("IdLivro");

                    b.HasIndex("IdAutor");

                    b.HasIndex("IdGenero");

                    b.ToTable("Livros");

                    b.HasData(
                        new
                        {
                            IdLivro = 1,
                            AnoPublicacao = "1845",
                            Descricao = "Poema narrativo sobre um homem atormentado pelo corvo que visita sua casa durante a noite.",
                            IdAutor = 1,
                            IdGenero = 1,
                            NPaginas = 100,
                            Titulo = "O Corvo"
                        },
                        new
                        {
                            IdLivro = 2,
                            AnoPublicacao = "1843",
                            Descricao = "Conto psicológico que explora a culpa e a paranoia de um assassino que acredita ouvir o coração da vítima batendo sob o assoalho.",
                            IdAutor = 1,
                            IdGenero = 1,
                            NPaginas = 120,
                            Titulo = "O Coração Delator"
                        },
                        new
                        {
                            IdLivro = 3,
                            AnoPublicacao = "1887",
                            Descricao = "Primeiro romance de Sherlock Holmes, onde ele e Dr. Watson investigam um assassinato misterioso.",
                            IdAutor = 2,
                            IdGenero = 3,
                            NPaginas = 200,
                            Titulo = "Um Estudo em Vermelho"
                        },
                        new
                        {
                            IdLivro = 4,
                            AnoPublicacao = "1902",
                            Descricao = "Sherlock Holmes investiga uma lenda sobre um cão fantasmagórico que assombra a família Baskerville.",
                            IdAutor = 2,
                            IdGenero = 3,
                            NPaginas = 180,
                            Titulo = "O Cão dos Baskervilles"
                        },
                        new
                        {
                            IdLivro = 5,
                            AnoPublicacao = "1928",
                            Descricao = "Conto que introduz o horror cósmico de Cthulhu, uma entidade antiga que aguarda adormecida.",
                            IdAutor = 3,
                            IdGenero = 1,
                            NPaginas = 150,
                            Titulo = "A Chamada de Cthulhu"
                        },
                        new
                        {
                            IdLivro = 6,
                            AnoPublicacao = "1936",
                            Descricao = "Uma expedição à Antártica descobre ruínas antigas e criaturas terríveis que desafiam a compreensão humana.",
                            IdAutor = 3,
                            IdGenero = 1,
                            NPaginas = 170,
                            Titulo = "Nas Montanhas da Loucura"
                        },
                        new
                        {
                            IdLivro = 7,
                            AnoPublicacao = "1818",
                            Descricao = "Um cientista cria uma criatura grotesca em um experimento ousado que desafia os limites da ciência e da moralidade.",
                            IdAutor = 4,
                            IdGenero = 1,
                            NPaginas = 220,
                            Titulo = "Frankenstein"
                        },
                        new
                        {
                            IdLivro = 8,
                            AnoPublicacao = "1819",
                            Descricao = "Uma jovem luta com sentimentos proibidos por seu pai distante e se vê envolvida em um dilema emocional intenso.",
                            IdAutor = 4,
                            IdGenero = 2,
                            NPaginas = 130,
                            Titulo = "Mathilda"
                        },
                        new
                        {
                            IdLivro = 9,
                            AnoPublicacao = "1926",
                            Descricao = "Um dos mais famosos romances policiais de Agatha Christie, conhecido por seu final surpreendente.",
                            IdAutor = 5,
                            IdGenero = 3,
                            NPaginas = 190,
                            Titulo = "O Assassinato de Roger Ackroyd"
                        },
                        new
                        {
                            IdLivro = 10,
                            AnoPublicacao = "1934",
                            Descricao = "Hercule Poirot investiga um assassinato ocorrido em um luxuoso trem europeu.",
                            IdAutor = 5,
                            IdGenero = 3,
                            NPaginas = 210,
                            Titulo = "Assassinato no Expresso Oriente"
                        },
                        new
                        {
                            IdLivro = 11,
                            AnoPublicacao = "1977",
                            Descricao = "Um escritor aceita um emprego como zelador de um hotel isolado e descobre que o local abriga segredos aterrorizantes.",
                            IdAutor = 6,
                            IdGenero = 1,
                            NPaginas = 240,
                            Titulo = "O Iluminado"
                        },
                        new
                        {
                            IdLivro = 12,
                            AnoPublicacao = "1986",
                            Descricao = "Um grupo de crianças enfrenta seus medos mais profundos quando um mal antigo ressurge na cidade de Derry.",
                            IdAutor = 6,
                            IdGenero = 1,
                            NPaginas = 280,
                            Titulo = "It: A Coisa"
                        },
                        new
                        {
                            IdLivro = 13,
                            AnoPublicacao = "1897",
                            Descricao = "O clássico romance que introduziu o lendário vampiro Conde Drácula ao mundo.",
                            IdAutor = 7,
                            IdGenero = 1,
                            NPaginas = 260,
                            Titulo = "Drácula"
                        },
                        new
                        {
                            IdLivro = 14,
                            AnoPublicacao = "1903",
                            Descricao = "Um arqueólogo britânico desafia antigas maldições ao desenterrar um túmulo egípcio em Londres.",
                            IdAutor = 7,
                            IdGenero = 2,
                            NPaginas = 150,
                            Titulo = "O Diamante das Sete Estrelas"
                        });
                });

            modelBuilder.Entity("Biblioteca.Models.Usuario", b =>
                {
                    b.Property<int>("IdUsuario")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Cpf")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("UsuarioDesde")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("IdUsuario");

                    b.ToTable("usuarios");
                });

            modelBuilder.Entity("Biblioteca.Models.Emprestimo", b =>
                {
                    b.HasOne("Biblioteca.Models.Livro", "Livro")
                        .WithMany()
                        .HasForeignKey("IdLivro")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Biblioteca.Models.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("IdUsuario")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Livro");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("Biblioteca.Models.Livro", b =>
                {
                    b.HasOne("Biblioteca.Models.Autor", "Autor")
                        .WithMany()
                        .HasForeignKey("IdAutor")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Biblioteca.Models.Genero", "Genero")
                        .WithMany()
                        .HasForeignKey("IdGenero")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Autor");

                    b.Navigation("Genero");
                });
#pragma warning restore 612, 618
        }
    }
}
